name: the_shop
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  cached_network_image: ^3.3.1
  retrofit: ^4.0.1
  dev: ^1.0.0
  dio: ^5.3.0
  freezed: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  auto_route: ^7.7.0
  intl: ^0.18.1
  decimal: ^2.3.3
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1
  auto_route_generator: ^7.2.0

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
